# An example docker-compose.yml for run on devcontainer.

version: "3.5"

services:
  # Primary application service
  app:
    user: "vscode:vscode"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile  
      args:
        - PORT=${APP_MAIN_PORT}
        - RUBY_VERSION=${RUBY_VERSION}
        - NODE_JS_VERSION=${NODE_JS_VERSION}
        - BUNDLE_VERSION=${BUNDLE_VERSION} 
    ports:
      - ${APP_MAIN_PORT}:${APP_MAIN_PORT}
    volumes:
      - ..:/app:cached
      - $HOME/.ssh/:/home/vscode/.ssh/
    command: sleep infinity
    networks:
      - network_shared

  # MySQL database service
  mysql:
    image: mysql:5.7
    env_file:
      - path: ./mysql_devcontainer.env
        required: true
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_shared

  # PostgreSQL database service
  postgres:
    image: postgres:12-alpine
    env_file:
      - path: ./postgres_devcontainer.env
        required: true    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - network_shared

  # Memcached service
  memcached:
    image: memcached:1.5-alpine
    ports:
      - ${MEMCACHED_PORT}:11211
    networks:
      - network_shared

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBIT_MQ_PORT_1}:5672
      - ${RABBIT_MQ_PORT_2}:15672
    networks:
      - network_shared

  # Redis service
  redis:
    image: redis:4.0.10-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    networks:
      - network_shared

  # OpenSearch service
  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - ${OPEN_SEARCH_PORT}:9200
    environment:
      - discovery.type=single-node
    networks:
      - network_shared

  # Mailcatcher service
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - ${MAIL_CATCHER_PORT}:1080
    networks:
      - network_shared

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
  opensearch_data:
    driver: local

networks:
  network_shared:
    external: true
    name: network_shared
